//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca_Movil.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Obra", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Obra : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int id_obraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        private System.DateTime fecha_publicacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string categoriaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id_obra {
            get {
                return this.id_obraField;
            }
            set {
                if ((this.id_obraField.Equals(value) != true)) {
                    this.id_obraField = value;
                    this.RaisePropertyChanged("id_obra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime fecha_publicacion {
            get {
                return this.fecha_publicacionField;
            }
            set {
                if ((this.fecha_publicacionField.Equals(value) != true)) {
                    this.fecha_publicacionField = value;
                    this.RaisePropertyChanged("fecha_publicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string categoria {
            get {
                return this.categoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.categoriaField, value) != true)) {
                    this.categoriaField = value;
                    this.RaisePropertyChanged("categoria");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ServicioWebSoap")]
    public interface ServicioWebSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/autenticacion", ReplyAction="*")]
        Biblioteca_Movil.ServiceReference1.autenticacionResponse autenticacion(Biblioteca_Movil.ServiceReference1.autenticacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/autenticacion", ReplyAction="*")]
        System.Threading.Tasks.Task<Biblioteca_Movil.ServiceReference1.autenticacionResponse> autenticacionAsync(Biblioteca_Movil.ServiceReference1.autenticacionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consulta_Obras", ReplyAction="*")]
        Biblioteca_Movil.ServiceReference1.consulta_ObrasResponse consulta_Obras(Biblioteca_Movil.ServiceReference1.consulta_ObrasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consulta_Obras", ReplyAction="*")]
        System.Threading.Tasks.Task<Biblioteca_Movil.ServiceReference1.consulta_ObrasResponse> consulta_ObrasAsync(Biblioteca_Movil.ServiceReference1.consulta_ObrasRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class autenticacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="autenticacion", Namespace="http://tempuri.org/", Order=0)]
        public Biblioteca_Movil.ServiceReference1.autenticacionRequestBody Body;
        
        public autenticacionRequest() {
        }
        
        public autenticacionRequest(Biblioteca_Movil.ServiceReference1.autenticacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class autenticacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contraseña;
        
        public autenticacionRequestBody() {
        }
        
        public autenticacionRequestBody(string nombre, string contraseña) {
            this.nombre = nombre;
            this.contraseña = contraseña;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class autenticacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="autenticacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Biblioteca_Movil.ServiceReference1.autenticacionResponseBody Body;
        
        public autenticacionResponse() {
        }
        
        public autenticacionResponse(Biblioteca_Movil.ServiceReference1.autenticacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class autenticacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int autenticacionResult;
        
        public autenticacionResponseBody() {
        }
        
        public autenticacionResponseBody(int autenticacionResult) {
            this.autenticacionResult = autenticacionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consulta_ObrasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consulta_Obras", Namespace="http://tempuri.org/", Order=0)]
        public Biblioteca_Movil.ServiceReference1.consulta_ObrasRequestBody Body;
        
        public consulta_ObrasRequest() {
        }
        
        public consulta_ObrasRequest(Biblioteca_Movil.ServiceReference1.consulta_ObrasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consulta_ObrasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        public consulta_ObrasRequestBody() {
        }
        
        public consulta_ObrasRequestBody(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consulta_ObrasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consulta_ObrasResponse", Namespace="http://tempuri.org/", Order=0)]
        public Biblioteca_Movil.ServiceReference1.consulta_ObrasResponseBody Body;
        
        public consulta_ObrasResponse() {
        }
        
        public consulta_ObrasResponse(Biblioteca_Movil.ServiceReference1.consulta_ObrasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consulta_ObrasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Biblioteca_Movil.ServiceReference1.Obra consulta_ObrasResult;
        
        public consulta_ObrasResponseBody() {
        }
        
        public consulta_ObrasResponseBody(Biblioteca_Movil.ServiceReference1.Obra consulta_ObrasResult) {
            this.consulta_ObrasResult = consulta_ObrasResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioWebSoapChannel : Biblioteca_Movil.ServiceReference1.ServicioWebSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioWebSoapClient : System.ServiceModel.ClientBase<Biblioteca_Movil.ServiceReference1.ServicioWebSoap>, Biblioteca_Movil.ServiceReference1.ServicioWebSoap {
        
        public ServicioWebSoapClient() {
        }
        
        public ServicioWebSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioWebSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWebSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWebSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Biblioteca_Movil.ServiceReference1.autenticacionResponse Biblioteca_Movil.ServiceReference1.ServicioWebSoap.autenticacion(Biblioteca_Movil.ServiceReference1.autenticacionRequest request) {
            return base.Channel.autenticacion(request);
        }
        
        public int autenticacion(string nombre, string contraseña) {
            Biblioteca_Movil.ServiceReference1.autenticacionRequest inValue = new Biblioteca_Movil.ServiceReference1.autenticacionRequest();
            inValue.Body = new Biblioteca_Movil.ServiceReference1.autenticacionRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.contraseña = contraseña;
            Biblioteca_Movil.ServiceReference1.autenticacionResponse retVal = ((Biblioteca_Movil.ServiceReference1.ServicioWebSoap)(this)).autenticacion(inValue);
            return retVal.Body.autenticacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Biblioteca_Movil.ServiceReference1.autenticacionResponse> Biblioteca_Movil.ServiceReference1.ServicioWebSoap.autenticacionAsync(Biblioteca_Movil.ServiceReference1.autenticacionRequest request) {
            return base.Channel.autenticacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Biblioteca_Movil.ServiceReference1.autenticacionResponse> autenticacionAsync(string nombre, string contraseña) {
            Biblioteca_Movil.ServiceReference1.autenticacionRequest inValue = new Biblioteca_Movil.ServiceReference1.autenticacionRequest();
            inValue.Body = new Biblioteca_Movil.ServiceReference1.autenticacionRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.contraseña = contraseña;
            return ((Biblioteca_Movil.ServiceReference1.ServicioWebSoap)(this)).autenticacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Biblioteca_Movil.ServiceReference1.consulta_ObrasResponse Biblioteca_Movil.ServiceReference1.ServicioWebSoap.consulta_Obras(Biblioteca_Movil.ServiceReference1.consulta_ObrasRequest request) {
            return base.Channel.consulta_Obras(request);
        }
        
        public Biblioteca_Movil.ServiceReference1.Obra consulta_Obras(string nombre) {
            Biblioteca_Movil.ServiceReference1.consulta_ObrasRequest inValue = new Biblioteca_Movil.ServiceReference1.consulta_ObrasRequest();
            inValue.Body = new Biblioteca_Movil.ServiceReference1.consulta_ObrasRequestBody();
            inValue.Body.nombre = nombre;
            Biblioteca_Movil.ServiceReference1.consulta_ObrasResponse retVal = ((Biblioteca_Movil.ServiceReference1.ServicioWebSoap)(this)).consulta_Obras(inValue);
            return retVal.Body.consulta_ObrasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Biblioteca_Movil.ServiceReference1.consulta_ObrasResponse> Biblioteca_Movil.ServiceReference1.ServicioWebSoap.consulta_ObrasAsync(Biblioteca_Movil.ServiceReference1.consulta_ObrasRequest request) {
            return base.Channel.consulta_ObrasAsync(request);
        }
        
        public System.Threading.Tasks.Task<Biblioteca_Movil.ServiceReference1.consulta_ObrasResponse> consulta_ObrasAsync(string nombre) {
            Biblioteca_Movil.ServiceReference1.consulta_ObrasRequest inValue = new Biblioteca_Movil.ServiceReference1.consulta_ObrasRequest();
            inValue.Body = new Biblioteca_Movil.ServiceReference1.consulta_ObrasRequestBody();
            inValue.Body.nombre = nombre;
            return ((Biblioteca_Movil.ServiceReference1.ServicioWebSoap)(this)).consulta_ObrasAsync(inValue);
        }
    }
}
